### ISSUE TITLE
hey mate help me out here

### ISSUE THREAD

**Issue by baran321** [HerrEurobeat/steam-comment-service-bot#38] opened 2020-06-07 03:49 UTC
**Describe the bug**
I did everything you did in the video nothing more or less 
**SyntaxError: C:\Users\olena\OneDrive\Desktop\commentbot\steam-comment-service-bot-master\logininfo.json: Unexpected token } in JSON at position 57**
Please post the **complete** error here!
PS C:\Users\olena\OneDrive\Desktop\commentbot\steam-comment-service-bot-master> node start.js
internal/modules/cjs/loader.js:1175
    throw err;
    ^

SyntaxError: C:\Users\olena\OneDrive\Desktop\commentbot\steam-comment-service-bot-master\logininfo.json: Unexpected token } in JSON at position 57
    at parse (<anonymous>)
[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1172:22)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\olena\OneDrive\Desktop\commentbot\steam-comment-service-bot-master\src\controller.js:6:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:986:32)[39m
PS C:\Users\olena\OneDrive\Desktop\commentbot\steam-comment-service-bot-master>

**Comment by HerrEurobeat** [comment] 2020-06-07 09:47
Hi, thanks for opening an issue!
As far as I can see this doesn't seem like a bug - more like an invalid syntax in your logininfo.json.

Could you please make sure that your logininfo.json follows exactly this pattern:

```
{
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"]
}
```

**Comment by baran321** [comment] 2020-06-07 13:23
same issue that the ways I tried
1){
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"]
}
2) "bot0": ["username0", "password0"]
3)"bot0": ["username0", "password0"],

**Comment by HerrEurobeat** [comment] 2020-06-07 13:52
Hm, I'm not sure what you mean.
If you use the exact pattern like the example I provided and you just filled in your username and password it should work just fine. 
How many accounts do you use? Maybe you haven't correctly shortened or extended the logininfo.
If you aren't using that many accounts you could also censor your usernames and passwords and send the content of your file here.

Make sure that:
- After every line **except** after the last line it has a comma at the end
- That the file starts with `{` and ends with `}`
- That your usernames and passwords are inside the `"` quotes

**Comment by baran321** [comment] 2020-06-07 13:56
{
	"bot0": ["hourboost23", "User:elz651lf8q@mail.ru"],
	"bot1": ["say1j_acrygw", "pass:sadkha;ildfha;ilh:@PE(Q)O(HD@Q)(d12"],
	"bot2": ["jenkersonsouleymane97", "Password:1xzri0a4e"]
}

**Comment by HerrEurobeat** [comment] 2020-06-07 14:02
Your passwords are weird
The password bracket must only contain the password, not a `User:`, `pass:` or `Password:` infront of it.
And I have never seen an email as a password

```
{
"bot0": ["hourboost23", "mypassword"],
"bot1": ["say1j_acrygw", "mypassword"],
"bot2": ["jenkersonsouleymane97", "mypassword"]
}
```

Just replace `mypassword` with your actual password in your logininfo. Everything else seems fine.

**Comment by baran321** [comment] 2020-06-07 14:20
lel they are very safe and hard to crack xD let me try

**Comment by HerrEurobeat** [comment] 2020-06-07 14:22
Hm I'm actually not sure what happens then. Since your passwords are in quotes it technically shouldn't be a problem but since I can't really find anything else I assumed this could be the cause. Maybe you have another account with a simpler password that you could try.

**Comment by baran321** [comment] 2020-06-07 14:26
ok ill try with a easier password

**Comment by baran321** [comment] 2020-06-07 14:45
and thx for releasing and helping ppl out with this tutorial its great 
i have to still figure later about it the job is grea tho

**Comment by HerrEurobeat** [comment] 2020-06-09 10:52
Hey, is it working for you now with another password? 
(and I hope you have changed your passwords if the above ones were correct)

**Comment by baran321** [comment] 2020-06-09 14:10
Hey huh it didn't work

**Comment by HerrEurobeat** [comment] 2020-06-12 13:55
Woops, didn't mean to do that.
I'm going to close this one, please respond if you are still facing this issue and need help.
Thanks!

**Closed** 2020-06-12 13:55 UTC
Labels: bug
