### ISSUE TITLE
controller.js

### ISSUE THREAD

**Issue by zacharykkkk** [HerrEurobeat/steam-comment-service-bot#19] opened 2020-05-02 21:35 UTC
[2020-05-03 05:31:59] Logging in... Estimated wait time: 1.76 minutes.

*------------------------------------------*
C:\comment\src\controller.js:171
        logger(`\x1b[96m${logininfo.bot0[0]}\x1b[0m version ${extdata.version} by 3urobeat logged in.`, true)
                                        ^

TypeError: Cannot read property '0' of undefined
    at Timeout._onTimeout (C:\comment\src\controller.js:171:41)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

got this error. any idea how to fix it?

**Comment by HerrEurobeat** [comment] 2020-05-02 22:59
Hey, thanks for opening an issue!

It seems like something in your logininfo.json is formatted wrong.
Is your logininfo.json formatted just like in the example?

`{
	"bot0": ["username0", "password0"],
	"bot1": ["username1", "password1"],
	"bot2": ["username2", "password2"]
}`

Be sure not to share your username and password though.

**Comment by zacharykkkk** [comment] 2020-05-03 12:51
alright fixed! thanks. i've met with another error. :(

TypeError: Cannot read property 'time' of undefined
    at SteamUser.<anonymous> (C:\comment\src\bot.js:241:429)
    at SteamUser.emit (events.js:310:20)
    at SteamUser._emitIdEvent (C:\comment\node_modules\steam-user\components\utility.js:28:12)
    at SteamUser.<anonymous> (C:\comment\node_modules\steam-user\components\chatroom.js:56:8)
    at C:\comment\node_modules\steam-user\components\classes\HandlerManager.js:37:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (C:\comment\node_modules\steam-user\components\classes\HandlerManager.js:36:12)
    at SteamUser._handleMessage (C:\comment\node_modules\steam-user\components\messages.js:545:24)
    at SteamUser._handleNetMessage (C:\comment\node_modules\steam-user\components\messages.js:480:7)
    at SteamUser.processMulti (C:\comment\node_modules\steam-user\components\messages.js:572:9)

**Comment by HerrEurobeat** [comment] 2020-05-03 13:00
Hey, good to hear that the first error is fixed.
Can you provide a bit more information about when the second error pops up?
It seems like it is coming from the !info command, therefore it would be interesting if the error was caused when you used the command or if it already comes up on startup?

Please try to unfriend your main bot and send him a friend request again. That should fix the error for now.

**Comment by zacharykkkk** [comment] 2020-05-03 13:11
i tried unfriending but doesn't work. here's the top error.

C:\comment\src\bot.js:153
            if ((Date.now() - lastcomment[lastcommentsteamID].time) < (config.commentcooldown * 60000)) { //check if user has cooldown applied

**Comment by HerrEurobeat** [comment] 2020-05-03 13:37
Hm, weird. Another person messaged me yesterday with that error but I couldn't reproduce it. 
Could you please send me the content of your lastcomment.json file (located in the 'src' folder)? That could help me to understand what's going on. 
No worries, it only contains ID's, nothing log in relevant.

Maybe you could try refriending your bot again. The error seems to be caused because your entry is missing in the lastcomment.json and sending your bot a friend request should write you to it.

**Comment by zacharykkkk** [comment] 2020-05-03 14:39
{
    "7656119815539558916": {
        "time": 1588513106132,
        "bot": 1075327423
    },
    "7656119801609725941": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "7656119802300307941": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "7656119804646279941": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "7656119881748480741": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "7656119883004945741": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "7656119886050052941": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "7656119892294845441": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "7656119898146855241": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "7656119901228266541": {
        "time": 1588512378137,
        "bot": 311937036
    },
    "765611980153033462": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611981369538902": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611981967776172": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611981970026252": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611982226846802": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611982685359942": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611982876194982": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611983160321052": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611983253498282": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611983618681262": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611983676009442": {
        "time": 1588512411837,
        "bot": 257259789
    },
    "765611979726024171": {
        "time": 1588512412826,
        "bot": 226526275
    },
    "765611980281613051": {
        "time": 1588512412826,
        "bot": 226526275
    },
    "765611980347265491": {
        "time": 1588512412826,
        "bot": 226526275
    },
    "765611980925021901": {
        "time": 1588512412826,
        "bot": 226526275
    },
    "765611981193842881": {
        "time": 1588512412826,
        "bot": 226526275
    },
    "765611981223488891": {
        "time": 1588512412826,
        "bot": 226526275
    },
    "765611981226761731": {
        "time": 1588512412826,
        "bot": 226526275
    },
    "765611981270753361": {
        "time": 1588512412826,
        "bot": 226526275
    },
    "7656119821775448138": {
        "time": 1588512412978,
        "bot": 221655589
    },
    "7656119828639873338": {
        "time": 1588512412978,
        "bot": 221655589
    },
    "7656119810222127336": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119811936627536": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119815220178536": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119820136163036": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119825779763936": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119826348482136": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119829452653336": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119829992054136": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119835800669836": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119837972979536": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119839280782136": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119839852142536": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119840797505936": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119841117216936": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "7656119842025587736": {
        "time": 1588512413150,
        "bot": 455342503
    },
    "765611980372564234": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611980417848474": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611980612404254": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611980621084414": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611980679137434": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611981131761234": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611981433278604": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611981496340634": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611981713632974": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611981737994614": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611981747300704": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611981817096854": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982014120034": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982036445964": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982068079354": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982133891124": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982173021454": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982196818734": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982217040484": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982286317364": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982324154284": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982532456384": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982537399534": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982630360234": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982636744904": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982679311394": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982715130254": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982782832014": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982802119754": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611982809625404": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983021468804": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983380182824": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983395871154": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983403066184": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983464501774": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983486069914": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983498378664": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983656035574": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983704338664": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983714118414": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983840926684": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983869378144": {
        "time": 1588512416925,
        "bot": 871202114
    },
    "765611983928498284": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611983954789194": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611983972368704": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984088176604": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984122067164": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984128998844": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984174178134": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984176341754": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984202285044": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984204621674": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984272299844": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984303719764": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984421234434": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984423586564": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984479793574": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611984521429624": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988014443524": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988039133334": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988111049314": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988151599514": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988169331044": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988171619804": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988234606914": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988271646024": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988284797304": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988301225104": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988312262594": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988322022744": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988336687284": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988347568714": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988354835884": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988359767134": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988378946034": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988408041714": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988417112664": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988422074894": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988443785824": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988445867174": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988497327764": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988510364114": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988512273004": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988531429844": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988534013994": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988537722654": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988542042614": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988544718384": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988552596274": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988554250164": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988554902884": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988568333514": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988574583724": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988579989714": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988590855584": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988595768374": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988611400974": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988657750364": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988692828274": {
        "time": 1588512416926,
        "bot": 871202114
    },
    "765611988718476754": {
        "time": 1588512416926,
        "bot": 871202114
    }
}

**Comment by HerrEurobeat** [comment] 2020-05-03 14:56
Okay, well thats pretty long and a bit too long for me to find the error there.
Can you delete everything so that only this: `{}` is in the file and then restart the bot?

I'm sorry that I can't help you right out of the box but I just don't know from where the error is being caused.

**Comment by zacharykkkk** [comment] 2020-05-03 14:58
No worries brother. appreciate it your help! :)

**Comment by HerrEurobeat** [comment] 2020-05-03 15:39
Did you try what happens when you remove everything from the lastcomment.json except of `{}` and restart the bot?
When I do the same the bot instantly writes all his friends to the lastcomment.json again and I can request a comment without errors.

**Comment by HerrEurobeat** [comment] 2020-05-05 08:50
Hey, just wanting to ask back if you fixed the issue, if it has fixed itself or if the issue still persists.

**Comment by zacharykkkk** [comment] 2020-05-05 16:44
hey still having issues. i can only comment when the bot is logging into my accounts. once the bot has successfully logged in to all my accounts, they'll have an error.

**Comment by HerrEurobeat** [comment] 2020-05-07 07:34
Hey, sorry that I didn't answer.
Someone else now also has that error and I will try to push a patch asap.
I hope that you haven't abandoned ther bot yet ^^

**Comment by zacharykkkk** [comment] 2020-05-07 12:24
no worries brother. still hoping to use the bot as soon as it's fixed. ;)

anyway is there a feature for all the bots to join a particular steam group? tried configuring bot group or groupid64 and still doesn't work.

**Comment by HerrEurobeat** [comment] 2020-05-07 13:30
Configuring the botsgroupid with a group64id should enable the feature. The main bot should then invite all other bots to the group. Make sure the main bot can send group invites. I want to change this feature so that every bot joins that group instead of being invited because this would be easier.

**Comment by HerrEurobeat** [comment] 2020-05-07 20:45
Hey, I think I need you to test if this "duct tape solution" fixes the problem.
Please replace everything in your bot.js file (located in the `'src'` folder) with this: https://raw.githubusercontent.com/HerrEurobeat/steam-comment-service-bot/master/src/bot.js and report back if requesting a comment worked. Thanks!

**Comment by HerrEurobeat** [comment] 2020-05-15 17:42
Sorry that I waited so long before pushing the fix to master but here it finally is.  
If you are still recieving this message, please update your bot to `2.6.3`, try it out and close this issue if it works.  
Thanks!

Fixed in commit 29a0d82.

**Closed** 2020-05-16 16:15 UTC
Labels: bug, fixed, question
