### ISSUE TITLE
Bot crashes when trying to use certain stdout functions

### ISSUE THREAD

**Issue by stephanschorer** [HerrEurobeat/steam-comment-service-bot#48] opened 2020-07-02 18:35 UTC
As soon as I start the bot in the background for example with npm forever or pm2 the bot will instantly crash with the following error:

/"*path*to*steambot*"/updater.js:23
        process.stdout.clearLine()
                       ^

TypeError: process.stdout.clearLine is not a function
    at logger (/home/steambot/updater.js:23:24)
    at Object.<anonymous> (/home/steambot/updater.js:287:1)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/steambot/start.js:55:5)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
error: Forever detected script exited with code: 1

You should be able to reproduce the error, here a quick instruction for npm forever:

3. Run Node JS Server At Background Continuously With Forever
https://www.dev2qa.com/how-to-run-node-js-server-in-background/

**Comment by HerrEurobeat** [comment] 2020-07-02 19:15
Hi, thanks for opening an issue and letting me know that this error exists.
I could reproduce the error and it seems to be fixed by using the built in readline module instead of stdout. I will have to tinker a bit with it because it seems to be working slightly different but it will definitely be included in the next version.

**Comment by HerrEurobeat** [comment] 2020-07-03 18:15
Should be fixed in commit 8adc902 (Version 2.7.2). Thanks again for opening this issue!

**Comment by HerrEurobeat** [comment] 2023-04-06 08:39
Oh hey; that's weird!  
Which node.js & steam-comment-service-bot version are you using and on which OS is the bot running?  
It might be that an older node.js version lacks support for these methods.

**Comment by stephanschorer** [comment] 2023-04-06 08:59
oh my bad...

node: v19.8.1
pm2: v5.3.0
os: Ubuntu 20.04.6 LTS
commentbot: 2.12.5

**Comment by HerrEurobeat** [comment] 2023-04-06 17:02
Hmm, I'm using the same versions, just not on Ubuntu but on Arch. I might need to check if this is a Ubuntu specific problem, not sure why that should be the case though.  
Btw, does the bot crash on every start and also without pm2?

**Comment by stephanschorer** [comment] 2023-04-06 17:39
yes the crashes always happen with pm2 and no without pm2 everything works

**Comment by HerrEurobeat** [comment] 2023-06-05 12:47
Version 2.13 is out on master which fixes this issue.  
Check out the release notes [here](https://github.com/HerrEurobeat/steam-comment-service-bot/releases/tag/2.13.0)!

**Closed by HerrEurobeat** 2023-06-05 12:47 UTC
Labels: Bug, Fixed
