### ISSUE TITLE
This is one account running in a bot cluster.

### ISSUE THREAD

**Issue by mrranger** [HerrEurobeat/steam-comment-service-bot#2] opened 2020-01-16 06:12 UTC
This is one account running in a bot cluster.
Please add the main bot and send him a !help message.
If you want to check out what this is about, type: !about

**Comment by HerrEurobeat** [comment] 2020-01-16 10:51
Thank you for opening an issue! 
Although you didn't really described what the problem is, I already found the bug. 
Will be fixed in the next push!

**Comment by HerrEurobeat** [comment] 2020-01-16 11:21
Fixed in commit 30aa3ce.

**Closed by HerrEurobeat** 2020-01-16 11:21 UTC
Labels: bug, fixed
