### ISSUE TITLE
The bot is not completely started yet

### ISSUE THREAD

**Issue by RadicalRedemption** [HerrEurobeat/steam-comment-service-bot#80] opened 2021-03-10 19:02 UTC
The bot is not completely started yet. Please wait a moment before using a command.

Any idea how to make it work?

**Comment by HerrEurobeat** [comment] 2021-03-10 19:39
Hey, thanks for opening an issue. This message should disappear as soon as all accounts are logged in and the `Ready after x seconds` message is displayed in your terminal.

**Comment by RadicalRedemption** [comment] 2021-03-10 19:50
Well, this doesn't happen. There is a message waiting for websession.. and that's all, nothing else happens.

**Comment by HerrEurobeat** [comment] 2021-03-10 19:57
Hmm thats weird. I guess you have tried but I am going to ask anyway - Have you restarting the bot and does this happen every time?  
It could also maybe be a problem on your side; maybe internet, firewall or something like that. But I'm not sure and can't replicate this issue right now.

**Comment by RadicalRedemption** [comment] 2021-03-10 19:58
There is an active firewall, yes, but i have all Valve networks whitelisted. Does the bot make any other connections?

**Comment by RadicalRedemption** [comment] 2021-03-10 20:06
[2021-03-10 21:03:21] Logging in... Estimated wait time: 60 seconds.
[2021-03-10 21:04:58] [Bot 20] Account logged in! Waiting for websession...

After that, nothing happens. I disabled webserver option.

**Comment by HerrEurobeat** [comment] 2021-03-10 20:09
No, the only connections should be GitHub and SteamCommunity. And a firewall shouldn't prevent the bot from starting. Are all accounts logged in? Any other errors or messages in the `output.txt`?

**Comment by RadicalRedemption** [comment] 2021-03-10 20:13
There are no errors literally, all the accounts are logged in without any issues.

**Comment by RadicalRedemption** [comment] 2021-03-10 20:14
I am also using accounts.txt for importing accounts, i literally ignored logininfo.json and did not put anything there.

**Comment by HerrEurobeat** [comment] 2021-03-10 20:17
Okay I'm gonna test logging in my accounts using `accounts.txt` right now as I haven't tested it since implementing it.

**Comment by HerrEurobeat** [comment] 2021-03-10 20:21
Hm it works fine for me. Not sure right now what might cause this error. You could maybe try it with less accounts. Have you tried logging in with maybe only 3 accounts?

**Comment by RadicalRedemption** [comment] 2021-03-10 20:26
How do i specify the target account that will receive the comments by the way? I will try with less accounts once i know this.

**Comment by RadicalRedemption** [comment] 2021-03-10 20:30
Well, it suddenly started working after switching to logininfo.js lol

**Comment by HerrEurobeat** [comment] 2021-03-10 20:38
> How do i specify the target account that will receive the comments by the way? I will try with less accounts once i know this.

This is documented in the !help command and in the wiki: https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Commands-documentation  
You must be an owner to do this.  
`!comment 5 76561198260031749`

**Comment by RadicalRedemption** [comment] 2021-03-10 20:38
Would you please tell me how to make sure that one account won't post a comment more than once on a single steam profile?

**Comment by HerrEurobeat** [comment] 2021-03-10 20:38
> Well, it suddenly started working after switching to logininfo.js lol

Hm well thats weird. But at least it works now lol

**Comment by HerrEurobeat** [comment] 2021-03-10 20:39
> Would you please tell me how to make sure that one account won't post a comment more than once on a single steam profile?

Just set `repeatedComments` in the config to `1`.  
Config documentation: https://github.com/HerrEurobeat/steam-comment-service-bot/wiki/Config-documentation

**Comment by RadicalRedemption** [comment] 2021-03-10 20:58
Is it possible if i have 20 accounts in database and comment one account with 10 bots first time and second time with another 10 to make them comment with unique accounts every time?

**Comment by HerrEurobeat** [comment] 2021-03-10 21:31
No that is sadly not possible atm. You can either use the account order as in the logininfo or use `randomizeAccounts` to randomize the order.

**Comment by HerrEurobeat** [comment] 2021-03-16 17:14
I can confirm that others had this problem too when using the `accounts.txt`. I will try to find and fix the issue.

**Comment by HerrEurobeat** [comment] 2021-03-16 19:58
Update: It seems like this can happen when the accounts.txt has an empty line at the bottom. I added a check that will filter this line and it seems like this fixed this issue.

**Comment by HerrEurobeat** [comment] 2021-03-16 21:48
Fixed in 9aaea39 (Version 2.10.2).

**Closed by HerrEurobeat** 2021-03-16 21:48 UTC
Labels: bug, question
